Allow clippy::question_mark in xtask dist module
I think this might be a bug since clippy is flagging a lint from the
DeJson derive macro expansion that is coming from the external nanoserde
code (and not my own) when applied to the CheckMessage struct. I'm
not sure if there's a good way to solve this, but here's the macro
backtrace:

```
$ env RUSTFLAGS="-Z macro-backtrace" cargo +nightly clippy
error: this block may be rewritten with the `?` operator
   --> xtask/src/dist.rs:16:17
    |
16  | #[derive(Debug, DeJson)]
    |                 ^^^^^^ in this derive macro expansion
    |
   ::: /Users/abs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nanoserde-derive-0.1.19/src/lib.rs:118:1
    |
118 | pub fn derive_de_json(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    | -------------------------------------------------------------------------------- in this expansion of `#[derive(DeJson)]`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#question_mark
note: the lint level is defined here
   --> xtask/src/dist.rs:2:9
    |
2   | #![deny(clippy::all)]
    |         ^^^^^^^^^^^
    = note: `#[deny(clippy::question_mark)]` implied by `#[deny(clippy::all)]`
```