Allow publishing from detached HEAD state
I thought it would be fine referencing the $GITHUB_REF since that's what
we're actually checking out, but  cargo-release picks up "HEAD" instead.
This is the error it spits out:

> error: cannot release from branch "HEAD", instead switch to "refs/tags/spellabet-v0.1.0"

Related to https://github.com/EarthmanMuons/spellout/pull/77